status = [
    "test (ubuntu-latest, nightly)",
    "test (macOS-latest, nightly)",
    "test (windows-latest, nightly)",
    "style (clippy)",
    "style (rustfmt)",
]
block_labels = ["S-blocked"]
delete_merged_branches = true
use_squash_merge = true
