status = [
    "test (ubuntu-latest, nightly)",
    "test (macos-latest, nightly)",
    "test (windows-latest, nightly)",
    "style (clippy, ubuntu-latest)",
    "style (clippy, macos-latest)",
    "style (clippy, windows-latest)",
    "style (rustfmt, ubuntu-latest)",
    "style (rustfmt, macos-latest)",
    "style (rustfmt, windows-latest)",
    "shfmt",
    "shellcheck",
    "taiki-e.test",
]
block_labels = ["S-blocked"]
delete_merged_branches = true
use_squash_merge = true
