schedules:
  - cron: '0 1 * * *'
    displayName: Cron
    branches:
      include:
        - master
    always: true

trigger:
  - master
  - staging
  - trying

variables:
  RUSTFLAGS: -Dwarnings

jobs:
  - job: test
    strategy:
      matrix:
        linux:
          vmImage: ubuntu-latest
        macos:
          vmImage: macos-latest
        windows:
          vmImage: windows-latest
    pool:
      vmImage: $(vmImage)
    steps:
      - template: ci/azure-pipelines/install-rust.yml
        parameters:
          toolchain: nightly

  - job: clippy
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: ci/azure-pipelines/install-rust.yml
        parameters:
          toolchain: nightly
      - bash: |
          . ci/scripts/install-component.sh clippy
        displayName: Install clippy
      - bash: |
          cargo clippy --all
        displayName: cargo clippy

  - job: rustfmt
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: ci/azure-pipelines/install-rust.yml
        parameters:
          toolchain: nightly
      - bash: |
          . ci/scripts/install-component.sh rustfmt
        displayName: Install rustfmt
      - bash: |
          cargo fmt --all -- --check
        displayName: cargo fmt

  - job: rustdoc
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: ci/azure-pipelines/install-rust.yml
        parameters:
          toolchain: nightly
      - bash: |
          cargo doc --no-deps --all
        displayName: cargo doc
        env:
          RUSTDOCFLAGS: -Dwarnings
