[workspace]
resolver = "2"
members = [
    "rust/bin",
    "rust/lib",
    "rust/lib-no-std",
    "rust/lint",
    "tools/codegen",
]

# [profile.release]
# strip = true

[profile.dist]
inherits = "release"
strip = true
