[package]
name = "xarch-test"
version = "0.1.0"
edition = "2018"
publish = false

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]

[dependencies]
once_cell = "1"
