name: Create a new GitHub release
description: Create a new GitHub release

inputs:
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: 'false'

runs:
  using: node12
  main: main.js
