use std::{panic::Location, path::PathBuf};

pub fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    dir.pop(); // codegen
    dir.pop(); // tools
    dir
}

#[track_caller]
pub fn header(comment_token: &str, include_caller_location: bool) -> String {
    let mut out =
        format!("{} This file is @generated by {}.\n", comment_token, env!("CARGO_BIN_NAME"));
    out += &format!("{} It is not intended for manual editing.\n", comment_token);
    if include_caller_location {
        out += &format!("{}\n", comment_token);
        out += &format!("{} See {} for details.\n", comment_token, Location::caller().file());
    }
    out += "\n";
    out
}
