use std::{panic::Location, path::PathBuf};

pub fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    dir.pop(); // codegen
    dir.pop(); // tools
    dir
}

#[track_caller]
pub fn header(comment_token: &str, include_caller_location: bool) -> String {
    let mut out =
        format!("{comment_token} This file is @generated by {}.\n", env!("CARGO_BIN_NAME"));
    out += &format!("{comment_token} It is not intended for manual editing.\n");
    if include_caller_location {
        out += &format!("{comment_token}\n");
        out += &format!("{comment_token} See {} for details.\n", Location::caller().file());
    }
    out += "\n";
    out
}
