[target.armv7-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"

[target.thumbv7neon-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.powerpc64-unknown-linux-gnu]
linker = "powerpc64-linux-gnu-gcc"

[target.sparc64-unknown-linux-gnu]
linker = "sparc64-linux-gnu-gcc"
