steps:
  # Linux and macOS.
  - script: |
      set -e
      curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain none
      export PATH=$PATH:$HOME/.cargo/bin
      rustup toolchain install $RUST_TOOLCHAIN
      rustup default $RUST_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    env:
      RUST_TOOLCHAIN: ${{ parameters.toolchain }}
    displayName: Install rust (*nix)
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

  # Windows.
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --profile minimal --default-toolchain none
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      rustup toolchain install %RUST_TOOLCHAIN%
      rustup default %RUST_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    env:
      RUST_TOOLCHAIN: ${{ parameters.toolchain }}
    displayName: Install rust (windows)
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  # All platforms.
  - script: |
      rustup -V
      rustc -Vv
      cargo -V
    displayName: Query rust and cargo versions
