version: 1

update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    default_reviewers: []
    default_labels: []
    commit_message:
      prefix: "dependabot"
      include_scope: true
