version: 1

update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    default_reviewers: ["taiki-e"]
    default_assignees: ["taiki-e"]
    default_labels: []
