[package]
name = "cargo-hack"
version = "0.5.5"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/cargo-hack"
keywords = ["cargo", "subcommand", "testing"]
categories = [
    "command-line-utilities",
    "development-tools::cargo-plugins",
    "development-tools::testing",
]
exclude = ["/.*", "/tools"]
description = """
A cargo subcommand to provide some options useful for testing and continuous integration.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = "1.0.34"
ctrlc = { version = "3.1.4", features = ["termination"] }
serde_json = "1"
termcolor = "1"
terminal_size = "0.1.16"
toml = "0.5.2"

[dev-dependencies]
easy-ext = "0.2"
fs = { package = "fs-err", version = "2" }
once_cell = "1"
tempfile = "3"
walkdir = "2"
