name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev*
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  TIDY_EXPECTED_MARKDOWN_FILE_COUNT: 4
  TIDY_EXPECTED_RUST_FILE_COUNT: 5
  TIDY_EXPECTED_CLANG_FORMAT_FILE_COUNT: 0
  TIDY_EXPECTED_PRETTIER_FILE_COUNT: 8
  TIDY_EXPECTED_TOML_FILE_COUNT: 9
  TIDY_EXPECTED_SHELL_FILE_COUNT: 4
  TIDY_EXPECTED_DOCKER_FILE_COUNT: 1

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@main
    permissions:
      security-events: write # for github/codeql-action/*
    with:
      ruleset: false
      immutable-release: false
  codegen:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/gen.yml@main
    permissions:
      contents: write # for creating branch for pr
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}
    with:
      pr-token-app-client-id: ${{ vars.PR_TOKEN_APP_CLIENT_ID }}
  test:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-test.yml@main
    with:
      target: x86_64-unknown-linux-gnu,aarch64-apple-darwin,x86_64-pc-windows-msvc,aarch64-unknown-linux-gnu,x86_64-apple-darwin,x86_64-pc-windows-gnu

  test-tidy:
    needs: tidy
    env:
      TIDY_DEV: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          # NB: Sync list with https://github.com/taiki-e/checkout-action/blob/HEAD/.github/workflows/ci.yml
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
          - os: ubuntu-22.04
          - os: ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@v1
      # docker
      - run: tools/tidy.sh
      # https://github.com/ScribeMD/rootless-docker/pull/402
      - uses: AJGranowski/rootless-docker-action@23266b5b1fa508009c9ac4be4f8bde450fc3e269 # zizmor: ignore[stale-action-refs]
      - run: docker info -f '{{println .SecurityOptions}}' | grep -F rootless
      - run: tools/tidy.sh
      - run: |
          sudo systemctl stop docker.service || true
          sudo systemctl stop docker.socket || true
          sudo systemctl stop containerd.service || true
          sudo apt-get -qq -o Dpkg::Use-Pty=0 purge -y 'docker*'
          sudo rm -rf -- /etc/systemd/system/containerd.service
      # podman
      - run: |
          podman info | grep -F 'rootless: true'
      - run: TIDY_DOCKER_PATH=podman ./tools/tidy.sh
      # https://github.com/actions/runner-images/blob/HEAD/images/ubuntu/scripts/build/install-container-tools.sh
      - run: sudo apt-get -qq -o Dpkg::Use-Pty=0 purge -y podman buildah skopeo
      # nerdctl
      - name: Install nerdctl
        run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          # https://github.com/containerd/nerdctl/releases
          nerdctl_version=2.2.2
          case "$(uname -m)" in
            aarch64 | arm64) nerdctl_arch=arm64 ;;
            *) nerdctl_arch=amd64 ;;
          esac
          retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 "https://github.com/containerd/nerdctl/releases/download/v${nerdctl_version}/nerdctl-full-${nerdctl_version}-linux-${nerdctl_arch}.tar.gz" | sudo tar xzf - -C /usr/local
          if [[ "${OS}" != 'ubuntu-22.04'* ]]; then
            # https://rootlesscontaine.rs/getting-started/common/apparmor/
            sudo tee -- /etc/apparmor.d/usr.local.bin.rootlesskit >/dev/null <<EOF
          abi <abi/4.0>,
          include <tunables/global>

          /usr/local/bin/rootlesskit flags=(unconfined) {
            userns,

            # Site-specific additions and overrides. See local/README for details.
            include if exists <local/usr.local.bin.rootlesskit>
          }
          EOF
            sudo systemctl restart apparmor.service
          fi
          containerd-rootless-setuptool.sh install
        env:
          OS: ${{ matrix.os }}
      - run: nerdctl info -f '{{println .SecurityOptions}}' | grep -F rootless
      - run: TIDY_DOCKER_PATH=nerdctl ./tools/tidy.sh
