name: Coverage

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/github-actions/install-rust@main
        with:
          component: llvm-tools-preview
      - run: curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.1.0-alpha.3/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
      - run: cargo install rustfilt
      - run: |
          cargo llvm-cov --text > lcov.txt
          # cargo llvm-cov --lcov > lcov.info
          # cargo llvm-cov --json > lcov.json
      - run: |
          cat lcov.txt
          # cat lcov.info
          # cat lcov.json
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.txt
          # files: ./lcov.info
          # files: ./lcov.json
          fail_ci_if_error: true
          verbose: true
