name: Coverage

permissions:
  contents: read # write?

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Rust nightly and llvm-tools-preview
        run: rustup toolchain install nightly --component llvm-tools-preview && rustup default nightly
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --git https://github.com/taiki-e/cargo-llvm-cov.git --branch main
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --lcov > lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
