name: Debug

on:
  push:
    branches:
      - main
      - staging
      - debug

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest
          # - target: x86_64-pc-windows-gnu
          #   rust: nightly-x86_64-gnu
          #   os: windows-latest
          # - target: x86_64-unknown-linux-musl
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v2
      # - run: |
      #     ./tools/install.sh ${{ matrix.target }}
      #     rust-test-bin --help
      #   env:
      #     PACKAGE: rust-test-bin
      #     REPOSITORY: taiki-e/test
      #     TARGET: ${{ matrix.target }}
      # - run: |
      #     set -x
      #     rm -f ~/.cargo/bin/rust-test-bin
      #     ./tools/install-zip.sh ${{ matrix.target }}
      #     rust-test-bin --help
      #   env:
      #     PACKAGE: rust-test-bin
      #     REPOSITORY: taiki-e/test
      #     TARGET: ${{ matrix.target }}
