name: Debug

on:
  push:
    branches:
      - master
      - staging
      - debug
      - aarch64-gnu

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            arch: aarch64
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v2
      - name: cargo test --target ${{ matrix.target }}
        uses: uraimo/run-on-arch-action@v2.0.7
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          # githubToken: ${{ github.token }}
          install: |
            set -ex
            apt-get update -q -y
            apt-get install -q -y curl gcc cmake make
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
              | sh -s -- -y --profile minimal --default-toolchain nightly
          run: |
            source $HOME/.cargo/env
            rustup target add ${{ matrix.target }}
            cargo test --target ${{ matrix.target }}
            cargo run --bin rust-test-bin --target ${{ matrix.target }}
