name: shellcheck

on:
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/**'
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '00 01 * * *'

jobs:
  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install shfmt
        shell: bash
        run: |
          . ci/scripts/install-shfmt.sh
      - name: shfmt
        shell: bash
        run: |
          . ci/scripts/shfmt.sh check

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install shellcheck
        shell: bash
        run: |
          sudo apt install shellcheck
      - name: shellcheck
        shell: bash
        run: |
          shellcheck ci/scripts/*.sh
